var data = {
    'articles' : [

//Amphibians
    {
        "title" : "Restore linked habitat to protect tropical amphibians from disease: Study",
        "foto" : "foto art 1.jpg",
        "code" : 1,
        "category" : "Amphibians",
        "date" : 29-02-23,
        "views" : 4245,
        "author" : "Natanaele Bharat Elyj",
        "about" : "Natanaele Bharat Elyj is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 4,
        "profile" : "profile4.jpg",
        "content" : "Article:As a precipitous global biodiversity decline escalates, forests across the tropics are increasingly becoming fragmented. This fragmentation can lead to multiple problems, including a process known as “habitat split” that could have consequences for disease among amphibians, according to a recently published study in the journal Biological Reviews. Habitat split occurs when multiple “classes” of habitat — such as forests, streams and ponds — that are important to some amphibian species’ life cycles are separated, Gui Becker, first author on the paper and a biologist with Pennsylvania State University, told Mongabay in an interview.In earlier work, Becker and colleagues concluded that habitat split was a driving force behind local extinctions of amphibians in South America’s highly fragmented Atlantic Forest. However, a link between habitat split and the role of disease, had not then been considered.Of particular concern when it comes to amphibian disease is the chytrid fungus, Batrachochytrium dendrobatidis, which is linked to population declines in Brazil and to amphibian species losses across the globe. Also known as Bd, this fungus can cause the potentially fatal disease chytridiomycosis, with scientists already knowing prior to this research that habitat fragmentation can increase the risk of Bd infections among amphibians."
    },

    {
        "title" : "The 8 Best Pet Frogs For Beginners",
        "foto" : "foto art 2.jpg",
        "code" : 2,
        "category" : "Amphibians",
        "date" : 28-02-23,
        "views" : 4654,
        "author" : "Luciano Mars",
        "about" : "Luciano Mars is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 1,
        "profile" : "profile1.jpg",
        "content" : "The Amazon milk frog (Trachycephalus resinifictrix) is a well-liked species of frog among herp keepers. The Amazon milk frog is an arboreal species that typically hunt from perches in the tree tops near wooded areas. It is commonly raised in captivity and naturally reproduces in tree holes. Males’ sizes start at 2.5 inches and go up to 4 inches, while women’s sizes start at 2 inches. Their huge size, large hands, and large toe pads all help them in their tree-dwelling lifestyle. One of the largest native frogs in the Americas is the American bullfrog (Rana catesbeiana). The American bullfrog is a huge, powerful, and brutish frog that can reach a maximum length of about 8 inches. With their large, webbed feet, these frogs are excellent swimmers, and their ravenous appetites mean they can devour virtually any food item that fits in their mouths. The frog is an invasive species in many areas, and it can be found naturally in 36 U.S. states. The American bullfrog has been successfully bred in captivity, and its tadpoles may be obtained at most aquariums, pet stores, and reptile expos. The Argentine (or ornate, or Bell’s) horned frog (Ceratophrys ornata) is affectionately known as the Pac-Man frog due in part to the size of its mouth and the way in which it stuffs prey items into it. The frog is commonly kept in captivity, reproduced, and comes in a broad variety of morphs, making it a favorite among herp keepers. These amphibians reach a maximum size of around 6 inches, and they are not particularly energetic creatures, rather instead to wait patiently for prey to come to them.",
    },

    {
        "title" : "Global pet trade in amphibians is bigger than we thought",
        "foto" : "foto art 3.jpg",
        "code" : 3,
        "category" : "Amphibians",
        "date" : 27-02-23,
        "views" : 8745,
        "author" : "Silvestra Mariana",
        "about" : "Silvestra Mariana is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 3,
        "profile" : "profile3.jpg",
        "content" : "Humans keep all sorts of animals as pets and new species are constantly being brought into the trade – some reared in captivity, but many sourced from the wild. As a result, the global pet trade often puts wild populations at risk of over-exploitation. The Global Amphibian Assessment pegs 47 amphibian species to be predominantly threatened by unsustainable harvesting for the international pet trade. And the risks don’t end there. For various reasons, people release pets into the wild, resulting in biological invasions. People might do this because keeping the animal isn’t the experience they expected, or because they can’t afford it any longer. The problem is that, often, it may introduce a species to regions beyond their natural range. These invasive populations can harm native species and lead to the spread of diseases to new areas. For example, the pet trade is linked to the spread of an infectious fungal disease of salamanders in Europe, leading to large scale salamander mortality.These threats are especially true for amphibians (frogs, newts and caecilians). Amphibians are undergoing severe population declines all over the world due to habitat destruction, climate change, disease spread, and invasive species. Losing amphibians, pest-controllers par excellence, not only imperils agricultural security but can lead to imbalances in ecosystem processes.",
    },

    {
        "title" : "How to Take Care of a Pet Frog",
        "foto" : "foto art 4.jpg",
        "code" : 4,
        "category" : "Amphibians",
        "date" : 27-02-23,
        "views" : 8947,
        "author" : "Luciano Mars",
        "about" : "Luciano Mars is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 1,
        "profile" : "profile1.jpg",
        "content" : "First, it’s not so simple as just buying a frog. There are a ton of different frog species out there, and each has different needs and requirements, so you’ll need to research before you whip out your credit card. Different frogs can require completely different environments, so take everything on this list to be a guideline rather than a hard-and-fast rule. Buy a few books, ask knowledgeable breeders — do whatever you need to do to properly prepare yourself for owning your first frog. Your frog’s lifespan will depend on a variety of factors, including their species and your ability to properly care for them. On average, though, you can expect to commit 3 to 10 years to this pet, although it’s not unheard of for these animals to live much longer. Their sizes vary wildly as well, ranging from 1.5 to 5 inches. The overall size isn’t so important, as long as you know how big they’ll be once fully grown, as that will allow you to buy a tank of a suitable size.",
    },

//Birds

    {
        "title" : "Crowds flock to Beacon Hill Park as young owls learn to fly",
        "foto" : "foto art 5.jpg",
        "code" : 5,
        "category" : "Birds",
        "date" : 31-02-23,
        "views" : 9487,
        "author" : "Luciano Mars",
        "about" : "Luciano Mars is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 1,
        "profile" : "profile1.jpg",
        "content" : "Owlets start leaving nest around this time of year, so some people may come across young birds on the ground. Don't worry — it's a normal part of learning to fly. A family of great horned owls nesting in Beacon Hill Park is drawing crowds as the youngsters learn to fly. Photographers and birders flocked to the area this week after one of the young owls started leaving the nest to explore, known as “branching,” said Ann Nightingale, a volunteer with the Rocky Point Bird Observatory. The young owl ended up on the ground for a little while, a normal part of the process of learning to fly, she said."
    },

    {
        "title" : "Scientists are using machine learning to forecast bird migration and identify birds in flight by their calls",
        "foto" : "foto art 6.jpg",
        "code" : 6,
        "category" : "Birds",
        "date" : 27-02-23,
        "views" : 7493,
        "author" : "Luciano Mars",
        "about" : "Luciano Mars is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 1,
        "profile" : "profile1.jpg",
        "content" : "With chatbots like ChatGPT making a splash, machine learning is playing an increasingly prominent role in our lives. For many of us, it’s been a mixed bag. We rejoice when our Spotify For You playlist finds us a new jam, but groan as we scroll through a slew of targeted ads on our Instagram feeds. Machine learning is also changing many fields that may seem surprising. One example is my discipline, ornithology – the study of birds. It isn’t just solving some of the biggest challenges associated with studying bird migration; more broadly, machine learning is expanding the ways in which people engage with birds. As spring migration picks up, here’s a look at how machine learning is influencing ways to research birds and, ultimately, to protect them. The challenge of conserving migratory birds. Most birds in the Western Hemisphere migrate twice a year, flying over entire continents between their breeding and nonbreeding grounds. While these journeys are awe-inspiring, they expose birds to many hazards en route, including extreme weather, food shortages and light pollution that can attract birds and cause them to collide with buildings. Our ability to protect migratory birds is only as good as the science that tells us where they go. And that science has come a long way.",
    },

    {
        "title" : "Three of six escaped birds returned to Oakland zoo",
        "foto" : "foto art 7.jpg",
        "code" : 7,
        "category" : "Birds",
        "date" : 28-02-23,
        "views" : 1683,
        "author" : "Athanasia Lyric",
        "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 2,    
        "profile" : "profile2.jpg",
        "content" : "Three birds have been recovered and three others are still flying free at the Oakland Zoo after a tree fell onto an aviary there amid stormy weather earlier this week, a zoo spokesperson said Friday. Two pied crows, three superb starlings and a hooded vulture flew out of the aviary in the zoo's African Savanna area after the tree fell and tore the mesh on the structure during wet and windy conditions Tuesday. The three superb starlings, a small and brightly colored bird native to eastern Africa, flew back into their habitat and were recovered Thursday, but zoo staff still are trying to recover the crows and vulture, zoo spokesperson Isabella Linares said Friday. The three birds <q> are close by and on zoo grounds,</q> Linares said. Staff have eyes on the three birds still on the loose and are monitoring them 24 hours a day, she said. A pathway in the African Savanna area of the zoo where the tree fell had to close Thursday, so visitors that day were not able to see the African elephants further along that path, Linares said.",
    },

    {
        "title" : "Audubon annual backyard survey: Fewer birds seen",
        "foto" : "foto art 8.jpg",
        "code" : 8,
        "category" : "Birds",
        "date" : 28-02-23,
        "views" : 2849,
        "author" : "Silvestra Mariana",
        "about" : "Silvestra Mariana is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 3,
        "profile" : "profile3.jpg",
        "content" : "Early returns from New Hampshire Audubon’s annual Backyard Winter Bird Survey point to fewer birds at feeders this winter. Why? It turns out the answer is not simple. According to Dr. Pamela Hunt of N.H. Audubon, “There are many factors that influence the number of birds a person might see at their feeders during the winter, and most of them are not indicative of long-term population trends.” In winter, birds form feeding flocks and wander around in search of food. If food is plentiful they may not need to visit feeders except in bad weather. If food is scarce, many birds might leave entirely. Food means natural food crops called mast, the seeds from trees, weeds and fruit. Blue jays, for example, depend on acorns for food, and in the fall of 2022, they left the state because of a poor acorn crop. Other winter visitors, such as the familiar dark-eyed junco (or “snowbird”), migrate a variable distance depending on food availability. If food is scarce in the North, more will continue south to the mid-Atlantic, but they’ll stay put if there’s plenty to eat in northern New England. Then there are the birds called “winter finches,” including evening grosbeak and common redpoll. In most years, these birds are quite rare, but they can invade in huge numbers when their normal foods are hard to find in Canada. Even the familiar American goldfinch shows this pattern, although they are still present each winter.",
    },

//Fish

    {
        "title" : "Rockfish Genes Hold Clues To Human Longevity",
        "foto" : "foto art 9.jpg",
        "code" : 9,
        "category" : "Fish",
        "date" : 31-02-23,
        "views" : 8475,
        "author" : "Athanasia Lyric",
        "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 2,    
        "profile" : "profile2.jpg",
        "content" : "lorem ipsum",
    },

    {
        "title" : "A Fish Can Sense another’s Fear, A Study Shows",
        "foto" : "foto art 10.jpg",
        "code" : 10,
        "category" : "Fish",
        "date" : 29-02-23,
        "views" : 9375,
        "author" : "Luciano Mars",
        "about" : "Luciano Mars is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 1,
        "profile" : "profile1.jpg",
        "content" : "lorem ipsum",

    },

    {
        "title" : "Ancient Monster Fish “Dunk” Was Short and Chunky, Study Finds",
        "foto" : "foto art 11.jpg",
        "code" : 11,
        "category" : "Fish",
        "date" : 27-02-23,
        "views" : 8379,
        "author" : "Athanasia Lyric",
        "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 2,    
        "profile" : "profile2.jpg",
        "content" : "lorem ipsum",
    },

    {
        "title" : "Dolphin and Humans Work Together To Catch Fish In Brazil",
        "foto" : "foto art 12.jpg",
        "code" : 12,
        "category" : "Fish",
        "date" : 27-02-23,
        "views" : 2937,
        "author" : "Natanaele Bharat Elyj",
        "about" : "Natanaele Bharat Elyj is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 4,
        "profile" : "profile4.jpg",
        "content" : "lorem ipsum",
    },

//Mammals

    {
        "title" : "World's largest rodents are taking over a fancy gated community in Argentina",
        "foto" : "foto art 13.jpg",
        "code" : 13,
        "category" : "Mammals",
        "date" : 31-02-23,
        "views" : 10453,
        "author" : "Silvestra Mariana",
        "about" : "Silvestra Mariana is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 3,
        "profile" : "profile3.jpg",
        "content" : "lorem ipsum",
    },

    {
        "title" : "Woman Finds Clump Of Baby Squirrels In Her Yard And Helps Reunite Them With Mom",
        "foto" : "foto art 14.jpg",
        "code" : 14,
        "category" : "Mammals",
        "date" : 29-02-23,
        "views" : 8475,
        "author" : "Athanasia Lyric",
        "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 2,    
        "profile" : "profile2.jpg",
        "content" : "lorem ipsum",
    },

    {
        "title" : "Kitten Sneaks Out Of Crate To Comfort Scared Dog At The Vet",
        "foto" : "foto art 15.jpg",
        "code" : 15,
        "category" : "Mammals",
        "date" : 28-02-23,
        "views" : 8217,
        "author" : "Natanaele Bharat Elyj",
        "about" : "Natanaele Bharat Elyj is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 4,
        "profile" : "profile4.jpg",
        "content" : "lorem ipsum",
    },

    {
        "title" : "Hopeless Stray Dog Has The Sweetest Reaction When She Finally Finds Love",
        "foto" : "foto art 16.jpg",
        "code" : 16,
        "category" : "Mammals",
        "date" : 27-02-23,
        "views" : 1743,
        "author" : "Silvestra Mariana",
        "about" : "Silvestra Mariana is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 3,
        "profile" : "profile3.jpg",
        "content" : "lorem ipsum",
    },


//Reptiles

    {
        "title" : "What You Should Know About Pet Geckos",
        "foto" : "foto art 17.jpg",
        "code" : 17,
        "category" : "Reptiles",
        "date" : 31-02-23,
        "views" : 4345,
        "author" : "Natanaele Bharat Elyj",
        "about" : "Natanaele Bharat Elyj is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 4,
        "profile" : "profile4.jpg",
        "content" : "lorem ipsum",
    },


    {
        "title" : "How to Play With a Pet Lizard",
        "foto" : "foto art 18.jpg",
        "code" : 18,
        "category" : "Reptiles",
        "date" : 29-02-23,
        "views" : 2723,
        "author" : "Natanaele Bharat Elyj",
        "about" : "Natanaele Bharat Elyj is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 4,
        "profile" : "profile4.jpg",
        "content" : "lorem ipsum",
    },


    {
        "title" : "Are turtles reptiles or amphibians? Here’s what you need to know",
        "foto" : "foto art 19.jpg",
        "code" : 19,
        "category" : "Reptiles",
        "date" : 28-02-23,
        "views" : 3847,
        "author" : "Athanasia Lyric",
        "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 2,    
        "profile" : "profile2.jpg",
        "content" : "lorem ipsum",
    },


    {
        "title" : "How To Find (And Adopt) The Best Pet Snake For You",
        "foto" : "foto art 20.jpg",
        "code" : 20,
        "category" : "Reptiles",
        "date" : 27-02-23,
        "views" : 2847,
        "author" : "Athanasia Lyric",
        "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 2,    
        "profile" : "profile2.jpg",
        "content" : "lorem ipsum",
    },
    ],

'reviews' : [
        {
          "name": "Rachael Ray Nutrish Burger Bites Treats",
          "product": "produk 1.jpg",
          "categori":"Foods",
          "star":"4.5",
          "description":"Real beef is the #1 ingredient. These goodies break apart easily for smaller mouths, making them paw-fect for dogs of all sizes. Safely USA cooked with the world’s finest ingredients. Made without artificial flavors or meat by-products. There are no added grain ingredients.",
          "username1":"Lana Swan",
          "comment1":"My dog has poultry allergies, which makes it hard to find food, treats etc because everything has chicken/chicken broth or chicken bi-products now aways. My dog is very picky, but she loves these treats so much!",
          "username2":"David Nolan",
          "comment2":"Your dog will love these treats! I opened up the bag and my dog wanted to eat every single one of them he gets so excited when I am about to give him one.",
          "sku": 1,
        },
      
        {
          "name": "Chicken Apple Bark Treats for Dogs",
          "product": "produk 2.jpg",
          "categori":"Foods",
         "star":"4",
         "description":"Simple, healthy, and incredibly delicious, our baked Chicken Apple Bark Treats are made from chicken breast, potato starch, apples, mint, and parsley grown in the USA. Our high-quality treats are better than the average chicken-apple dog treats with no preservatives and serve as an excellent source of vitamins and fiber for a snack they'll love.",
         "username1":"C. Shepard",
         "comment1":"The ingredients are minimal, which is great. My dog got put on so many meds battling her autoimmune disease. She loved getting these and would do tricks for them. These trump all other pill pockets I've tried. I highly recommend.",
         "username2":"Leslie P.",
         "comment2":"My dog has colitis and a tendency for pancreatitis so I have to be careful of what treats she gets. She loves these treats and they are easy on her stomach.",
         "sku": 2,
        },
      
        {
          "name": "Presidio Pill Buddy Naturals",
          "product": "produk 3.jpg",
          "categori":"Foods",
         "star":"4",
         "description":"Pill Buddy Naturals is free of corn, wheat, soy and anything artificial. Just goodness. With real Peanut Butter & Apple because your pet deserves the best. A tasty way to give your best friend medicine. Hide a pill in the chewy treat.",
         "username1":"C. Shepard",
         "comment1":"The ingredients are minimal, which is great. My dog got put on so many meds battling her autoimmune disease. She loved getting these and would do tricks for them. These trump all other pill pockets I've tried. I highly recommend.",
         "username2":"L. Burge",
         "comment2":"Although these are a little pricey compared to Greenies brand, they are worth it. There are two treats wrapped in a bag. I have had this bag for months, and, when my pup just got neutered, they were as fresh as the day I got them, and my pup loves them.",
         "sku": 3,
        },
      
        {
          "name": "Zesty Paws Aller-Immune Bites",
          "product": "produk 4.jpg",
          "categori":"Foods",
          "star":"4.5",
          "description":"Specially formulated to support immune function and help fido with seasonal foes, with human-grade Epicor and other ingredients, and a delicious lamb, salmon, or peanut butter flavor fido will love!",
          "username1":"JT",
          "comment1":"I recently started using Aller Bites and switched my dog off food that contains chicken because she was constantly scratching and licking her feet and belly. Within a few weeks, the fur has grown back on her feet and areas where she was biting itchy spots. She's about 80 percent better now. I'll continue to use this product. She also likes the taste.",
          "username2":"Keisha",
          "comment2":"Adopted a 2yo GSD. She has a sensitive belly and would constantly scratch and chew. After using these chews, her belly has calmed down tremendously and very little chewing when we come back from outside.",
          "sku": 4,
        },
      
        {
          "name": "The Dodo Pet Bandanas",
          "product": "produk 5.jpg",
          "categori":"Accesories",
         "star":"5",
         "description":"Some dogs need a quick fashion fix — enter The Dodo Print Dog Bandana. Made from breathable, stretchy fabric, this bandana for dogs is comfortable for your pet and easy pet apparel for you to put on. This tie-on, triangular dog bandana is one size fits most, measuring 26” x 12”, and can simply be tied around your pet’s neck for every day or any occasion. The Dodo Print Dog Bandana features the name and signature colors of The Dodo in a fun abstract print, ensuring your pup will be selfie-ready from every angle. And here’s a pet parenting hack: Put the bandana in the freezer wet just before a walk in the heat to keep your pup cool!",
         "username1":"Joseph J.",
         "comment1":"The Dodo Dog Bandana Pet Apparel bandana is so cute and the material is great quality! The fabric is super soft which is a nice change from the stiffer fabrics we've seen from other brands. The polka dot pattern is perfect for the spring and summer.",
         "username2":"Jojo",
         "comment2":"The bandana is so cute. The sizing is perfect. I have a 85 pound boxer dog. His neck is huge. This fit around his neck perfectly. He looked so stylish with his new bandanna on.",
         "sku": 5,
        },
      
        {
          "name": "Alfie Pet Dexter Backpack Harness",
          "product": "produk 6.jpg",
          "categori":"Accesories",
         "star":"4",
         "description":"Functions as both a harness and backpack. Comes complete with a leash. Feature a sturdy D-ring for easy leash attachment. Perfect for everyday walk and weekend party, or just making your pet look its best",
         "username1":"Ashley O.",
         "comment1":"This is my favorite catch-all bag when walking my dog. I love that it has enough space to fit her water bottle and collapsable bowl, treats, toys, and doggy bags. It also doubles as a harness with a leash attachment, and it's super cute!",
         "username2":"Becky A.",
         "comment2":"We have a rescue pup about 24 pounds . It’s so fun and cute ! It’s big enough for treats and toys ! He loves his backpack ! Get it !!!",
         "sku": 6,
        },
      
        {
          "name": "Illumiseen LED Light Up Dog Leash",
          "product": "produk 7.jpg",
          "categori":"Accesories ",
         "star":"4",
         "description":"Our LED light up leash has 360-degree visibility up to 350 yards in any weather and any low light situation. This LED reflective belt is equipped with high intensity LED lights which provide high visibility in the dusk, nighttime, and any other low light situations. Vehicles will see you and your pet well in advance - ALL THE TIME",
         "username1":"Killian J.",
         "comment1":"I use this leash every time I walk my dog at night. I really love it and would give it a 5 stars except I wish the charge lasted longer. You do have to charge it sooner than I’d like but it’s still worth buying!",
         "username2":"Emma Millls",
         "comment2":"I use this because I often walk my dog in the dark at this time of year with the short days. We’ve had many comments from other walkers on what a great idea it is. The only negative is that I need 3 usb charger spots to charge the leash (2 sections) and collar.",
         "sku": 7,
        },
      
        {
          "name": "Tooth and Honey Pit Bull Pajamas",
          "product": "produk 8.jpg",
          "categori":"Accesories ",
          "star":"4.5",
          "description":"Unlike other brands Tooth & Honey designs original clothing specifically for REAL pit bull type dogs. Our fit is custom to our brand and our size chart/ styles were designed after fitting hundreds of pit bull type dogs including our own! Don't be fooled by the intimaters!",
          "username1":"Asha",
          "comment1":"It's always so hard to get clothes to fit bully breed's big chests, these clothes fit perfectly and are super cute as well",
          "username2":"Cherry S.",
          "comment2":"My pupper absolutely loves it! He is all smiles when wearing it. It’s a very comfortable material that stretch to allow breathing and moving room. He a short legged big guy, but I just went with the x-large. I wanted to make sure he had enough neck room and didn’t want it too saggy. My guy is a big fan of wearing clothes, and he brings this one from his room all the time so I can put it on him. I can’t wait to get more of these clothes from Tooth and Honey!",
          "sku": 8,
        },
      
        {
          "name": "Kong Classic Chew Toy",
          "product": "produk 9.jpg",
          "categori":"Toys",
          "star":"4.5",
          "description":"The KONG Classic red rubber toy helps satisfy dogs' instinctual needs while providing mental stimulation. Healthy play is important for dogs' physical and mental development, emotions and behavior. By encouraging healthy play and satisfying instinctual needs, this treat dispensing puzzle toy helps solve chewing, separation anxiety, teething, boredom, weight management, crate training, digging and barking",
          "username1":"Ruby R.",
          "comment1":"This is great for a dog who constantly chews. When our dog drops it, it rolls in circles so our dog can actually entertain himself. We occasionally put a finger full of peanut butter inside, but it only keeps him busy for about 20 seconds!!!",
          "username2":"Patty Gibson",
          "comment2":"These Kong toys work for some dogs, no so much for others. For my recent adoptions--two puppy-mill-mama rescues, this Kong style works well. Both dogs like to lick and chew to get the treats out, and that gives me a little time to myself. I wash both Kongs after each use.",
          "sku": 9,
        },
      
        {
          "name": "West Paw Zogoflex Hurley",
          "product": "produk 10.jpg",
          "categori":"Toys",
         "star":"4",
         "description":"If your pampered pooch is an aggressive chewer, then you’ll love the durable shapeand bouncy, floatable material of the West Paw Zogoflex Hurley Dog Bone Chew Toy. This durable dog bone chew toy is floatable and perfect for playing catch or fetch while in the water or on land.",
         "username1":"James C.",
         "comment1":"My labs usually chew through toys in minutes and days, but this has lasted for months and still going. Great to use in pool and lakes!",
         "username2":"Sebasian B.",
         "comment2":"I bought this because it will float when our dog puts it in the pond. It is kind of heavy, so don't throw it so it hits your dog.",
         "sku": 10,
        },
      
        {
          "name": "Hide-a-Squirrel Interactive Plushy",
          "product": "produk 11.jpg",
          "categori":"Toys",
         "star":"4",
         "description":"The Hide A Squirrel dog puzzle is an easy way to get your furry friends engaged for hours of fun! Just fill the tree trunk with 6 stuffed squeaky squirrels, toss it, and let your dog's natural hunting instincts kick in!",
         "username1":"Hannah G.",
         "comment1":"I ordered these to replace the ones that over the past few years have been kind of destroyed. I retired this before the foam inside start popping out and she might eat it. They are the go to toy for my Maltese so they get a lot of tooth activity. Plus, she likes to play tug-of-war a lot, so the tale makes it easier for me to grab and do battle with her.",
         "username2":"Johanna P.",
         "comment2":"No, these aren’t the most durable. But they are apparently the most fun my 3 year old puppy/dog can have. Even after she removes the squeaker she drags it around for a long time. We joke about having squirrel carcasses all over (sorry, bad joke!). But she plays with them for a long time. These are the only toys that she plays with that long. And every time we get a new one out I can see that puppy look in her eyes again",
         "sku": 11,
        },
      
        {
          "name": "Chukit! Ball Launcher",
          "product": "produk 12.jpg",
          "categori":"Toys",
         "star":"5",
         "description":"This ball toy for dogs entices play withhigh impact bouncing Play fetch at the lake or pool thanks to the lightweight, buoyant design. Compatible with Chuckit, ball launcher",
         "username1":"Nikki",
         "comment1":"The only ball I've found that my dog hasent destroyed so far. Has lasted awhile . Ive got a black lab/german shepard mix pup (shes big and chews alot) . I definitely would by again . Good brand and has held up . (So far , shes still growing).i got the two in pakage . Worth purchasing if u have a dog that just quit simply destroys dog toys or the regular tennis balls . Good buy for the price",
         "username2":"Kaylee Higby",
         "comment2":"My big guy loves playing fetch but tennis balls break as soon as he touches it because he likes chewing it on his way back. I’ve had these for 2 days so far and there isn’t a single mark on them which is SUPER impressive. The medium is the size of a standard tennis ball and VERY bouncy! I couldn’t be more pleased.",
         "sku": 12,
        },
      
        {
          "name": "Best Friends by Sheri Original Calming Donut Bed",
          "product": "produk 13.jpg",
          "categori":"Others",
          "star":"4.5",
          "description":"Thanks to its round shape, our high-quality Donut Cuddler cat and dog bed is ideal for pets who love to curl up. The raised rim creates a sense of security and provides head and neck support, while the super soft filling offers joint and muscle pain relief.",
          "username1":"Momo",
          "comment1":"Our dog loves it and we love that she loves it. Equally important, the cover comes off easily and can be washed. After washing with no softener and air drying in the dryer, it looks as good as new. Which is important when your dog sniffs out a few stray pieces of chocolate and gets it all over this bed when you are not home. I know the perils of chocolate for dogs and we are VERY cautious to scope out ALL surfaces she can jump on to make sure there are no future incidents.",
          "username2":"Nella",
          "comment2":"We have 3 little dogs and they absolutely LOVE these beds! The minute we put them down, they were just all over them! It was adorable watiching them enjoy the beds! We have just purchased our 4th bed and have replaced all the old beds! Easy to keep clean too! Thank you! Love this product!",
          "sku": 13,
        },
      
        {
          "name": "ZINUS Easy Pet Stairs",
          "product": "produk 14.jpg",
          "categori":"Others",
          "star":"4.5",
          "description":"High-density CertiPUR-US certified foam interior. Ideal for larger-sized pets. Removable and washable cozy cover. 22 inches high and 18 inches wide with 7 inch steps. Easy assembly",
          "username1":"Lauren H.",
          "comment1":"They're super helpful, they get a lot of use, and the design is pretty stylish, so they look great in my room. I'd recommend them for any pets who have mobility issues, senior pets, or super small pets who just need a boost.",
          "username2":"Jeb Henry",
          "comment2":"We have three smaller chihuahua mixes and these steps are perfect sized for them to climb up when we park this up against the sofa or loveseat",
          "sku": 14,
        },
      
        {
          "name": "K9 Sport Sack Plus 2",
          "product": "produk 15.jpg",
          "categori":"Others",
         "star":"4",
         "description":"The Air Plus is a backpack dog carrier with a multi-functional storage pack. The storage pack is great for bringing gear, treats, or other necessities along on your adventures. It also acts as a support for your dog’s back, pulling your pup in snuggly against your back",
         "username1":"Jane Y.",
         "comment1":"It makes it so easy to take Lucy on adventures where a normal side bag wouldn't work. It's a real attention grabber and she seems to really enjoy being in there!",
         "username2":"Laura-Ann Q.",
         "comment2":"Both my Havanese and I enjoy our K9 backpack. She like to use it to get the mail, go on walks, or just snuggle while I’m running errands.",
         "sku": 15,
        },
      
        {
          "name": "PETMAKER Waterproof Pet Blanket",
          "product": "produk 16.jpg",
          "categori":"Others",
          "star":"4.5",
          "description":"This cat and dog blanket features a PU water-resistant coating on one side to repel water, and the other side is covered with soft Sherpa fleece that soaks up liquids to effectively stop any moisture from passing through it.",
          "username1":"Marti T.",
          "comment1":"This blanket is actually waterproof, so you can put it on the sofa to prevent any accidents from leaking through. (It really does work!) Plus, the ivory option is nice and plush, so you can also just use it as a normal throw when you're not protecting your furniture. You wouldn't know it had a special purpose or that it was for a pup unless you noticed the paw print in the corner!",
          "username2":"Elizabeth Repa",
          "comment2":"Our dog is older and become slightly incontinent. This blanket gives us the confidence to allow our dog on the sofa without soiling our sofa.",
          "sku": 16,
        },
      
      ],

'aboutauthors' : [
    {
      "nama" : "",
      "about" : "Luciano Mars is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      "number": 1,
      "profile" : "profile1.jpg",
    
    },
    {
      "nama" : "Athanasia Lyric ",
      "about" : "Athanasia Lyric is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      "number": 2,    
      "profile" : "profile2.jpg",
    },
    {
      "nama" : "Silvestra Mariana",
        "about" : "Silvestra Mariana is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        "number": 3,
      "p  rofile" : "profile3.jpg",
    },
    {
      "nama" : "Natanaele Bharat Elyj",
      "about" : "Natanaele Bharat Elyj is Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      "number": 4,
      "profile" : "profile4.jpg",
    }
  ],
};   